name: Nightly release

on:
  workflow_dispatch:

concurrency: keycloak-release

jobs:

  keycloak-admin-console:
    name: Keycloak Admin Console
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      # actions/setup-java@v3.0.0
      uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: jboss-snapshots-repository
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Checkout Keycloak Admin UI repository
      # actions/checkout@v3.0.0
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      with:
        repository: 'stianst/keycloak-admin-ui'
        token: ${{ secrets.GH_TOKEN }}
        path: keycloak-admin-ui
        
    - name: Deploy Keycloak Admin UI
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}        
      working-directory: ./keycloak-admin-ui/keycloak-theme
      run: mvn -nsu -B -Pnexus-staging -DskipTests -DretryFailedDeploymentCount=10 -DautoReleaseAfterClose=true clean deploy

  keycloak:
    name: Keycloak
    runs-on: ubuntu-latest
    needs: [keycloak-admin-console]

    steps:
    - name: Setup Java
      # actions/setup-java@v3.0.0
      uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: jboss-snapshots-repository
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Checkout Keycloak repository
      # actions/checkout@v3.0.0
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      with:
        repository: 'keycloak/keycloak'
        token: ${{ secrets.GH_TOKEN }}
        path: keycloak
        
    - name: Download Keycloak Admin UI
      run: |
        mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=https://s01.oss.sonatype.org/content/repositories/snapshots/ -Dartifact=org.keycloak:keycloak-core:999-SNAPSHOT
      working-directory: ./keycloak
        
    - name: Update nightly tag
      run: |
        git tag -f nightly
        git push origin nightly --force
      working-directory: ./keycloak
        
    - name: Deploy Keycloak
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}        
      working-directory: ./keycloak
      run: mvn -nsu -B -Padmin-preview,gpg,jboss-release,nexus-staging,distribution-downloads -DskipTests -DskipTestsuite -DretryFailedDeploymentCount=10 -DautoReleaseAfterClose=true clean deploy
