name: Nightly release

on:
  workflow_dispatch:

concurrency: keycloak-release

jobs:
  keycloak:
    name: Keycloak
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: jboss-snapshots-repository
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Checkout Keycloak repository
      uses: actions/checkout@v3
      with:
        repository: 'stianst/keycloak'
        token: ${{ secrets.GH_TOKEN }}
        path: keycloak
        
    - name: Update nightly tag
      run: |
        git tag -f nightly
        git push origin nightly --force
      working-directory: ./keycloak
        
    - name: Deploy Keycloak
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}        
      working-directory: ./keycloak
      run: mvn -nsu -B -Pgpg,jboss-release,nexus-staging,distribution-downloads -DskipTests -DskipTestsuite -DretryFailedDeploymentCount=10 -DautoReleaseAfterClose=true clean deploy

    - name: Upload Keycloak release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release list -R stianst/keycloak | grep ^nightly >/dev/null && gh release delete -R stianst/keycloak nightly -y
        gh release create -R stianst/keycloak -p --target main --title nightly --notes "Nightly" nightly
        gh release upload -R stianst/keycloak nightly ./distribution/downloads/target/18.0.0-SNAPSHOT/*
      working-directory: ./keycloak
      
  keycloak-container:
    name: Keycloak Container
    runs-on: ubuntu-latest
    needs: [keycloak]

    steps:
    - name: Checkout Keycloak repository
      uses: actions/checkout@v3
      with:
        repository: 'stianst/keycloak'
        token: ${{ secrets.GH_TOKEN }}
        path: keycloak
        
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Container metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: quay.io/stianst/keycloak
        tags: |
          type=raw,value=nightly
          
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
        
    - name: Download Keycloak
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}    
      run: |
        gh release download -R stianst/keycloak -p keycloak-18.0.0-SNAPSHOT.tar.gz -D ./keycloak/quarkus/container nightly

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: keycloak/quarkus/container
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: KEYCLOAK_DIST=keycloak-18.0.0-SNAPSHOT.tar.gz
